### ISSUE TITLE
MySQL drops connection after a certain period.

### ISSUE THREAD

**Issue by AlpineMutts** [TUDelftMe/cecles#1]
We should probably make it reconnect every once in a while. Since now the server terminates due to the following error:

```
66.240.xxx.xxx - - [22/Mar/2015:16:12:28 +0000] "GET / HTTP/1.1" 302 40 "-" "-"
66.240.xxx.xxx - - [22/Mar/2015:16:12:29 +0000] "GET /robots.txt HTTP/1.1" 404 23 "-" "-"

Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/tudelftme/cecles/node_modules/mysql/lib/protocol/Protocol.js:103:13)
    at Socket.<anonymous> (/home/tudelftme/cecles/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by AlpineMutts** [comment]
Fixed in 89487f2915c2ddc6e882cbd2f0a2dd99f1f05360
